[project]
name = "video-sender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "aiortc>=1.11.0",
    "fastapi>=0.115.12",
    "opencv-python>=4.11.0.86",
    "uvicorn>=0.34.2",
]
